import { TimezoneOption } from './types';

export const COMMON_TIMEZONES: TimezoneOption[] = [
  { value: 'America/New_York', label: 'Eastern Time (ET)', offset: 'UTC-5/-4' },
  { value: 'America/Chicago', label: 'Central Time (CT)', offset: 'UTC-6/-5' },
  { value: 'America/Denver', label: 'Mountain Time (MT)', offset: 'UTC-7/-6' },
  { value: 'America/Los_Angeles', label: 'Pacific Time (PT)', offset: 'UTC-8/-7' },
  { value: 'America/Anchorage', label: 'Alaska Time (AKT)', offset: 'UTC-9/-8' },
  { value: 'Pacific/Honolulu', label: 'Hawaii Time (HST)', offset: 'UTC-10' },
  { value: 'UTC', label: 'UTC', offset: 'UTC+0' },
  { value: 'Europe/London', label: 'London (GMT/BST)', offset: 'UTC+0/+1' },
  { value: 'Europe/Paris', label: 'Paris (CET/CEST)', offset: 'UTC+1/+2' },
  { value: 'Europe/Berlin', label: 'Berlin (CET/CEST)', offset: 'UTC+1/+2' },
  { value: 'Europe/Moscow', label: 'Moscow (MSK)', offset: 'UTC+3' },
  { value: 'Asia/Dubai', label: 'Dubai (GST)', offset: 'UTC+4' },
  { value: 'Asia/Kolkata', label: 'India (IST)', offset: 'UTC+5:30' },
  { value: 'Asia/Bangkok', label: 'Bangkok (ICT)', offset: 'UTC+7' },
  { value: 'Asia/Singapore', label: 'Singapore (SGT)', offset: 'UTC+8' },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong (HKT)', offset: 'UTC+8' },
  { value: 'Asia/Shanghai', label: 'China (CST)', offset: 'UTC+8' },
  { value: 'Asia/Tokyo', label: 'Tokyo (JST)', offset: 'UTC+9' },
  { value: 'Asia/Seoul', label: 'Seoul (KST)', offset: 'UTC+9' },
  { value: 'Australia/Sydney', label: 'Sydney (AEST/AEDT)', offset: 'UTC+10/+11' },
  { value: 'Australia/Perth', label: 'Perth (AWST)', offset: 'UTC+8' },
  { value: 'Pacific/Auckland', label: 'Auckland (NZST/NZDT)', offset: 'UTC+12/+13' },
  { value: 'America/Sao_Paulo', label: 'Sao Paulo (BRT)', offset: 'UTC-3' },
  { value: 'America/Toronto', label: 'Toronto (ET)', offset: 'UTC-5/-4' },
  { value: 'America/Vancouver', label: 'Vancouver (PT)', offset: 'UTC-8/-7' },
];

export const TIME_FORMATS = {
  short: 'h:mm a',
  medium: 'h:mm:ss a',
  long: 'h:mm a ZZZZ',
  full: 'EEEE, MMMM d, yyyy h:mm a ZZZZ',
  iso: "yyyy-MM-dd'T'HH:mm:ssZZ",
};

export const TIMEZONE_ABBREVIATIONS: Record<string, string> = {
  // Standard abbreviations
  'EST': 'America/New_York',
  'EDT': 'America/New_York',
  'CST': 'America/Chicago',
  'CDT': 'America/Chicago',
  'MST': 'America/Denver',
  'MDT': 'America/Denver',
  'PST': 'America/Los_Angeles',
  'PDT': 'America/Los_Angeles',
  'AKST': 'America/Anchorage',
  'AKDT': 'America/Anchorage',
  'HST': 'Pacific/Honolulu',
  'GMT': 'UTC',
  'UTC': 'UTC',
  'BST': 'Europe/London',
  'CET': 'Europe/Paris',
  'CEST': 'Europe/Paris',
  'IST': 'Asia/Kolkata',
  'JST': 'Asia/Tokyo',
  'AEST': 'Australia/Sydney',
  'AEDT': 'Australia/Sydney',
  'AWST': 'Australia/Perth',
  'NZST': 'Pacific/Auckland',
  'NZDT': 'Pacific/Auckland',
  // Short forms
  'PT': 'America/Los_Angeles',
  'ET': 'America/New_York',
  'CT': 'America/Chicago',
  'MT': 'America/Denver',
  'AKT': 'America/Anchorage',
  'HT': 'Pacific/Honolulu',
  // Full timezone names
  'PACIFIC': 'America/Los_Angeles',
  'EASTERN': 'America/New_York',
  'CENTRAL': 'America/Chicago',
  'MOUNTAIN': 'America/Denver',
  'ALASKA': 'America/Anchorage',
  'HAWAII': 'Pacific/Honolulu',
  // Common variations
  'PACIFIC TIME': 'America/Los_Angeles',
  'EASTERN TIME': 'America/New_York',
  'CENTRAL TIME': 'America/Chicago',
  'MOUNTAIN TIME': 'America/Denver',
  'ALASKA TIME': 'America/Anchorage',
  'HAWAII TIME': 'Pacific/Honolulu',
  // International
  'LONDON': 'Europe/London',
  'UK': 'Europe/London',
  'PARIS': 'Europe/Paris',
  'BERLIN': 'Europe/Berlin',
  'TOKYO': 'Asia/Tokyo',
  'SYDNEY': 'Australia/Sydney',
  'SINGAPORE': 'Asia/Singapore',
  'HONG KONG': 'Asia/Hong_Kong',
  'INDIA': 'Asia/Kolkata',
  'DUBAI': 'Asia/Dubai',
};
